### PR TITLE
Fix local build

### LINKED ISSUE #388: Local build is broken
### Description

Local build is broken when running `.\build.ps1`j:
Reason for this is, that `Microsoft.NET.Test.Sdk` must not be included 

### Reproduction Steps

```
.\build.ps1
```

### Expected behavior

The build should succeed

### Actual behavior

The build fails with
```
╬══════════════════════
║ Errors & Warnings
╬═════════════
​
[ERR] Compile: C:\temp\AwesomeAssertions\Tests\Benchmarks\Program.cs(13,24): error CS0017: Program has more than one entry point defined. Compile with /main to specify the type that contains the entry point. [C:\temp\AwesomeAssertions\Tests\Benchmarks\Benchmarks.csproj::TargetFramework=net8.0]
[ERR] Compile: C:\temp\AwesomeAssertions\Tests\Benchmarks\Program.cs(13,24): error CS0017: Program has more than one entry point defined. Compile with /main to specify the type that contains the entry point. [C:\temp\AwesomeAssertions\Tests\Benchmarks\Benchmarks.csproj::TargetFramework=net8.0]
[ERR] Compile: Target Compile has thrown an exception
​
═════════════════════════════════════════════════
Target                       Status      Duration
─────────────────────────────────────────────────
InstallNode                  Succeeded       0:01   // Skipped: Downloading and extracting
SpellCheck                   Succeeded       0:03
Clean                        Succeeded     < 1sec
Restore                      Succeeded       0:03
CalculateNugetVersion        Succeeded     < 1sec
Compile                      Failed          1:30   // Version: 9.3.1-foo.1
```

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

This broke with #364 when adding `Microsoft.NET.Test.Sdk` to the `Tests/Directory.Build.props`, and with this also the the benchmark project.

### Are you willing to help with a pull-request?

Yes, please assign this issue to me.

### PR DESCRIPTION
**Pull request by cbersch**
Fix #388 
## IMPORTANT 

* [ ] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [ ] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/main/Tests/AwesomeAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/main/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://awesomeassertions.org/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/main/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/main/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/main/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://awesomeassertions.org/introduction).
    * [ ] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

## Legal checklist

* [ ] This work is entirely original, it is not derived from any existing code incompatible with the Apache 2.0 License, like FluentAssertions.

### CODE REVIEW

**Review by lg2de — COMMENTED** [review]
I'm wondering why local build is affected while server build is not affected.

**Comment by cbersch** [comment]
I don't know, maybe the configuration. On the server we build with "CI", the local build is with "Debug".
Haven't investigated that more in depth, took me a while to figure out why it broke at all.

**Comment by cbersch** [comment]
> Do you know why we need this CI configuration?

I think it's to build the actual assembly as "Release", but all specs with "Debug", so that the caller extraction stuff works.
