### ISSUE TITLE
Local build is broken

### ISSUE THREAD

**Issue by cbersch** [AwesomeAssertions/AwesomeAssertions#388]
### Description

Local build is broken when running `.\build.ps1`j:
Reason for this is, that `Microsoft.NET.Test.Sdk` must not be included 

### Reproduction Steps

```
.\build.ps1
```

### Expected behavior

The build should succeed

### Actual behavior

The build fails with
```
╬══════════════════════
║ Errors & Warnings
╬═════════════
​
[ERR] Compile: C:\temp\AwesomeAssertions\Tests\Benchmarks\Program.cs(13,24): error CS0017: Program has more than one entry point defined. Compile with /main to specify the type that contains the entry point. [C:\temp\AwesomeAssertions\Tests\Benchmarks\Benchmarks.csproj::TargetFramework=net8.0]
[ERR] Compile: C:\temp\AwesomeAssertions\Tests\Benchmarks\Program.cs(13,24): error CS0017: Program has more than one entry point defined. Compile with /main to specify the type that contains the entry point. [C:\temp\AwesomeAssertions\Tests\Benchmarks\Benchmarks.csproj::TargetFramework=net8.0]
[ERR] Compile: Target Compile has thrown an exception
​
═════════════════════════════════════════════════
Target                       Status      Duration
─────────────────────────────────────────────────
InstallNode                  Succeeded       0:01   // Skipped: Downloading and extracting
SpellCheck                   Succeeded       0:03
Clean                        Succeeded     < 1sec
Restore                      Succeeded       0:03
CalculateNugetVersion        Succeeded     < 1sec
Compile                      Failed          1:30   // Version: 9.3.1-foo.1
```

### Other information

This broke with #364 when adding `Microsoft.NET.Test.Sdk` to the `Tests/Directory.Build.props`, and with this also the the benchmark project.

### Are you willing to help with a pull-request?

Yes, please assign this issue to me.
